**CODEAZA PYTHON ASSIGNMENT 03**

***Ojbectives***

Perform the following tasks

Variable in Module

Rename Module

Built-in Modules

List All Defined Names of Modules (use dir)

Import a specific function from a module

Import Modules From A Folder

Write 6 use cases of Modules

**VARIABLES in Modules**

Normally modules contain functions but they can also contain variables, lists, dictionaires etc.

In [1]:
import intern
# Accessing the dictionaly variables keys declared in intern module file
print(intern.intern1["name"])
print(intern.intern1["age"])
print(intern.intern1["University"])
print(intern.intern1["CGPA"])

print(intern.Company)

Hammad Khan
23
Air University
2.9
Codeaza Technologies


**Rename Module**

We rename our modules to avoid wasting time by writing complete name of module again and again to access it, instead we rename it to some smaller keyword

for example, we import pandas as pd

In [2]:
import intern as it

print(it.Company)


Codeaza Technologies


**BUILT-IN Modules**

There are a lot of built-in modules in Python. Some of the important ones are - pandas, numpy, sckitlearn, tensorflow, math, os, pip, sys, and time.

In [3]:
import math
import datetime
print(math.sqrt(25))  # Square root
print(math.pi)  # Value of pi



today_date = datetime.date.today()
print(today_date)  # Print today's date

cur_time = datetime.datetime.now().time()
print(cur_time)  # Print the current time

import numpy as np

# Create a 1-dimensional array
array1 = np.array([1, 2, 3, 4, 5])
print(array1)

# Create a 2-dimensional array
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array2)


5.0
3.141592653589793
2023-06-22
23:00:23.772479
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**USE dir() to list the members of module**
The dir() function in Python can be used to list all the defined names (functions, classes, variables, etc.) within a module.

In [4]:
import intern
import numpy

defined_names = dir(intern)

# Print the defined names in our module
for names in defined_names:
    print(names)
defined_names2 = dir(numpy)

# Print the defined names
for names2 in defined_names2:
    print("\n",names2)



Company
__builtins__
__cached__
__doc__
__file__
__loader__
__name__
__package__
__spec__
find_pattern
intern1
re

 ALLOW_THREADS

 AxisError

 BUFSIZE

 CLIP

 ComplexWarning

 DataSource

 ERR_CALL

 ERR_DEFAULT

 ERR_IGNORE

 ERR_LOG

 ERR_PRINT

 ERR_RAISE

 ERR_WARN

 FLOATING_POINT_SUPPORT

 FPE_DIVIDEBYZERO

 FPE_INVALID

 FPE_OVERFLOW

 FPE_UNDERFLOW

 False_

 Inf

 Infinity

 MAXDIMS

 MAY_SHARE_BOUNDS

 MAY_SHARE_EXACT

 ModuleDeprecationWarning

 NAN

 NINF

 NZERO

 NaN

 PINF

 PZERO

 RAISE

 RankWarning

 SHIFT_DIVIDEBYZERO

 SHIFT_INVALID

 SHIFT_OVERFLOW

 SHIFT_UNDERFLOW

 ScalarType

 Tester

 TooHardError

 True_

 UFUNC_BUFSIZE_DEFAULT

 UFUNC_PYVALS_NAME

 VisibleDeprecationWarning

 WRAP

 _CopyMode

 _NoValue

 _UFUNC_API

 __NUMPY_SETUP__

 __all__

 __builtins__

 __cached__

 __config__

 __deprecated_attrs__

 __dir__

 __doc__

 __expired_functions__

 __file__

 __getattr__

 __git_version__

 __loader__

 __name__

 __package__

 __path__

 __spec__

 __

**Import a specific function from a module**

Defining the find_pattern function in module and calling it here

In [6]:
from intern import find_pattern

# Example usage
input_string = "Hi, My name is Hammad Khan and I am python developer intern at Codeaza technologies."
pattern = r'Hammad Khan'  
result = find_pattern(pattern, input_string)
print(result)


['Hammad Khan']


**IMPORT MODULE from different folder**

We can import module from different folders in python using from folder_name import module_name or if we want to access specific function of module, use from folder_name.module_name import func

In [7]:
from module_folder import intern2
# Accessing the dictionaly variables keys declared in intern module file
print(intern2.intern1["name"])
print(intern2.intern1["age"])
print(intern2.intern1["University"])
print(intern2.intern1["CGPA"])

print(intern2.Company)

ABC
34
Air University
22.4
Codeaza Technologies


In [8]:
from module_folder.intern2 import find_pattern
input_string = "Hi, My name is Hammad Khan and I am python developer intern at Codeaza technologies."
pattern = r'Hammad Khan'  # Find words with exactly 5 characters

result = find_pattern(pattern, input_string)
print(result)


['Hammad Khan']


** USE CASES Of Modules **
Module are useful and essential entities of python. they are helpful when we have very large projects and it is splitted in several files.

6 use cases of modules are :

1.  Use pre-trained ML models instead of training them again.
2.  Use built-in functions of python to reduce code complexity.
3.  Modules like scikit-learn, tensorflow, and pytorch are extensively used in machine learning and AI projects.
4.  Use to connect databases in python.
5.  Modules such as os and shutil offer functions to work with files and directories
6.  Use to perform complex mathematical computations without needing to right compelete code again.